home:
  controller: WebSite\Controller\HomeController:homeAction

list_user:
  controller: WebSite\Controller\UserController:listUserAction

show_user:
  controller: WebSite\Controller\UserController:showUserAction

delete_user:
  controller: WebSite\Controller\UserController:deleteUserAction

add_user:
  controller: WebSite\Controller\UserController:addUserAction

log_user:
   controller: WebSite\Controller\UserController:logUserAction

logout_user:
   controller: WebSite\Controller\UserController:logOutUserAction